### ISSUE TITLE
Have a function to return the rest of the buffer.

### ISSUE THREAD

**Issue by bofh69** [envis10n/libtelnet-rs#14]
From the MUD Client Compression Protocol (MCCP2) protocol description:
"When a client connects to a server the server should send IAC WILL MCCP2. The client should respond with either IAC DO MCCP2 or IAC DONT MCCP2. If the server receives IAC DO MCCP2 it should respond with: IAC SB MCCP2 IAC SE and immediately afterwards start compressing data."

This can not be implemented correctly with libtelnet-rs because the bytes following IAC SE may already have been sent to Parser's buffer. There need to be a way for the Parser to stop parsing the buffer after the IAC SE and return the rest of the bytes unparsed so they can be sent through the decompressor instead.

This is needed to fix [MCCP2 starts too late in the stream #139](https://github.com/LiquidityC/Blightmud/issues/139).

**Comment by envis10n** [comment]
Wouldn't this be better handled by checking if the parser had the mccp2 option enabled and decompressing / compressing before / after transmission through the parser?

The way I understand what you're saying, the bytes are garbled because they are compressed and cannot be parsed properly without being decompressed first. Which would mean that the decompression needs to occur before it hits the parser.

Sorry ninja edit 2: I see what you mean. Immediately after it is negotiated, there is still data that needs to be decompressed that may still be in the parser buffer. I'll take a look at fixing this tonight

**Comment by LiquidityC** [comment]
I have "coded around" this feature on Blightmud so far. I have two suggestions for a solution:

1. Introduce a special event `TelnetEvents::MCCP2Subnegotation(TelnetSubnegotation, Vec<u8>)` where the vector holds the remainder of the bytes in the current buffer (buffer is cleared in libtelnet)
2. Introduce a value `Option<Vec<u8>>` on `TelnetSubnegotation` that can hold the remainder of the buffer in "special cases" (MCCP2 for example).

**Comment by envis10n** [comment]
Work on this has been submitted to mccp_fix branch. Give me some time to arrange testing and get confirmation that it will actually work out.

**Comment by LiquidityC** [comment]
I've adapted to this in Blightmud. Seems to work solid out of the box. :trophy:

**Comment by LiquidityC** [comment]
Tested and implemented. Works just grand :trophy:
